name: Terraform Sanity Check

# Kiedy ten pipeline ma ruszyć?
on:
  push:
    branches: [ "main" ]
  pull_request:

# Co robot ma zrobić?
jobs:
  terraform-check:
    name: Sprawdź Kod
    runs-on: ubuntu-latest # GitHub użyczy nam swojego serwera z Linuxem

    steps:
    # 1. Pobierz Twój kod z repozytorium
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Zainstaluj Terraforma na serwerze GitHuba
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 3. Zainicjuj Terraforma (pobierz wtyczki)
    - name: Terraform Init
      run: terraform init -backend=false
      # -backend=false oznacza: "nie próbuj łączyć się z chmurą/klastrem, testujemy tylko kod"

    # 4. Sprawdź czy kod jest ładnie wcięty (Format)
    - name: Terraform Format
      run: terraform fmt -check

    # 5. Sprawdź czy kod jest poprawny składniowo (Validate)
    - name: Terraform Validate
      run: terraform validate